<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <groupId>es.idee.api</groupId>
   <artifactId>api-idee-parent</artifactId>
   <version>1.1.0</version>
   <packaging>pom</packaging>
   <name>API IDEE PARENT</name>
   <description>Herramienta para desarrollo de mapas interactivos de forma sencilla</description>
   <properties>
      <project.release.date>${maven.build.timestamp}</project.release.date>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <build.timestamp>${maven.build.timestamp}</build.timestamp>
      <maven.build.timestamp.format>dd-MM-yyyy</maven.build.timestamp.format>
      <log4j2.version>2.25.3</log4j2.version>
   </properties>
   <dependencyManagement>
      <dependencies>
         <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-bom</artifactId>
            <version>${log4j2.version}</version>
            <type>pom</type>
            <scope>import</scope>
         </dependency>
      </dependencies>
   </dependencyManagement>
   <modules>
      <module>../api-idee-js</module>
      <module>../api-idee-proxy</module>
      <module>../api-idee-database</module>
      <module>../api-idee-rest</module>
   </modules>
   <licenses>
      <license>
         <name>European Union Public Licence - EUPL v.1.1</name>
         <url>LICENSE.txt</url>
      </license>
   </licenses>
   <developers>
      <developer>
         <organization>Guadaltel S.A.</organization>
         <organizationUrl>www.guadaltel.com</organizationUrl>
      </developer>
   </developers>
   <profiles>
     <profile>
        <id>local</id>
        <activation>
           <activeByDefault>false</activeByDefault>
        </activation>
        <properties>
           <environment>local</environment>
        </properties>
     </profile>
     <profile>
        <id>cnig-desarrollo</id>
        <activation>
           <activeByDefault>true</activeByDefault>
        </activation>
        <properties>
           <environment>cnig-desarrollo</environment>
        </properties>
     </profile>
   </profiles>
   <build>
      <pluginManagement>
         <plugins>
            <plugin>
               <artifactId>maven-release-plugin</artifactId>
               <version>2.5</version>
               <configuration>
                  <preparationGoals>clean package</preparationGoals>
                  <autoVersionSubmodules>true</autoVersionSubmodules>
                  <tagNameFormat>APIIDEE_v@{project.version}_@{maven.build.timestamp}</tagNameFormat>
               </configuration>
            </plugin>
            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-compiler-plugin</artifactId>
               <version>2.3.2</version>
            </plugin>
            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-dependency-plugin</artifactId>
               <version>2.0</version>
            </plugin>
            <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-assembly-plugin</artifactId>
               <version>2.1</version>
            </plugin>
         </plugins>
      </pluginManagement>
   </build>
      <dependencies>
         <dependency>
         <groupId>commons-io</groupId>
         <artifactId>commons-io</artifactId>
         <version>1.4</version>
      </dependency>
      <dependency>
        <groupId>org.apache.httpcomponents</groupId>
	     <artifactId>httpclient</artifactId>
	     <version>4.5.2</version>
      </dependency>
   </dependencies>
</project>
