# CSS
mobile.width=768

# zooms
maxZoom=28
minZoom=0
defaultZoom=3

# DEPLOYMENT
api-idee.url=http://10.67.33.46:9010/api-idee/
api-idee.proxy.url=//10.67.33.46:9010/api-idee/api/proxy
api-idee.proxy_post.url=//10.67.33.46:9010/api-idee/proxyPost
api-idee.static_resources.url=https://componentes.idee.es/estaticos
api-idee.theme.url=//10.67.33.46:9010/api-idee/assets/
plugins.external.base.url=https://componentes.idee.es/api-idee-communityplugins
wmc.urls=https://componentes.idee.es/estaticos/Datos/WMC/mapa.xml,https://componentes.idee.es/estaticos/Datos/WMC/hibrido.xml,https://componentes.idee.es/estaticos/Datos/WMC/satelite.xml,https://componentes.idee.es/estaticos/Datos/WMC/context_cdau_callejero.xml,https://componentes.idee.es/estaticos/Datos/WMC/context_cdau_hibrido.xml,https://componentes.idee.es/estaticos/Datos/WMC/context_cdau_satelite.xml,https://componentes.idee.es/estaticos/Datos/WMC/contextCallejeroCache.xml,https://componentes.idee.es/estaticos/Datos/WMC/contextCallejero.xml,https://componentes.idee.es/estaticos/Datos/WMC/callejero2011cache.xml,https://componentes.idee.es/estaticos/Datos/WMC/ortofoto2011cache.xml,https://componentes.idee.es/estaticos/Datos/WMC/hibrido2011cache.xml,https://componentes.idee.es/estaticos/Datos/WMC/contextOrtofoto.xml
wmc.predefinedNames=mapa,hibrido,satelite,cdau,cdau_hibrido,cdau_satelite,callejerocacheado,callejero,callejero2011cache,ortofoto2011cache,hibrido2011cache,ortofoto
wmc.names=Mapa,Hibrido,Satelite,Callejero,Hibrido,Satelite,mapa callejero cache,mapa del callejero,Callejero,Ortofoto,Híbrido,mapa ortofoto

# LAYERS
baseLayer=QUICK*Base_IGNBaseTodo_TMS
terrain.default=QUICK*MDT_TERRAIN
services=WMS,WMS_FULL,KML,LayerGroup,WFST,WMTS,GeoJSON,GeoTIFF,MBTilesVector,MBTiles,MapLibre,MVT,OGCAPIFeatures,OSM,TMS,XYZ,GenericRaster,GenericVector,Vector,Terrain,Tiles3D,GeoPackage,GeoPackageTile

# PROJECTION
api-idee.proj.default=EPSG:3857

# CONTROLS
controls=scale,scaleline,panzoombar,panzoom,location,getfeatureinfo,rotate,backgroundlayers,attributions,implementationswitcher
controls.default=
zoomLocation=16

# WASM
sql_wasm.url=//10.67.33.46:9010/api-idee/wasm/

# VERSIONS
versions.names=1.0.0,latest

# rest configuration
proxy.host=192.168.192.11
proxy.port=8080

# MAIL
smtp.host=10.67.32.151
smtp.port=
smtp.user=
smtp.password=
smtp.remitente=mail-cnig-noreply@cnig.es

# SECURITY DATABASE CONNECTOR
database.whitelist=10.67.33.46
database.blacklist=
#Type of list to use for source validation (white o black)
database.list=white